Repository redbadger/website-honestly, pull requests merged in 2018-03, with the labels that each got.

#696 New innovation and delivery header
  site/css/typography/_fonts.css
  site/pages/what-we-do/header-slice/arrow.png
  site/pages/what-we-do/header-slice/index.js
  site/pages/what-we-do/header-slice/style.css
  site/pages/what-we-do/index.js
  site/pages/what-we-do/style.css
Labels: In Test

#701 Update sub-heading
  assets/manifest.json
  site/pages/home/homepage-top-slice/index.js
  site/pages/home/index.js
Labels: In Test

#698 Lean agile process slice
  site/pages/what-we-do/index.js
  site/pages/what-we-do/lean-agile-slice/index.js
  site/pages/what-we-do/lean-agile-slice/largeLoop.svg
  site/pages/what-we-do/lean-agile-slice/smallLoop.svg
  site/pages/what-we-do/lean-agile-slice/style.css
  site/pages/what-we-do/lean-slice/index.js
  site/pages/what-we-do/lean-slice/lean.png
  site/pages/what-we-do/lean-slice/styles.css
Labels: In Test

#705 Update issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Needs testing

#710 Remove bugsnag fork dependency
  package.json
Labels: Needs testing

#711 Add missing import statement
  services/mailchimp/update-user/index.js
Labels: Needs testing

#697 Cross functional team slice
  site/components/colour-box/index.js
  site/components/colour-box/style.css
  site/components/image/index.js
  site/components/image/style.css
  site/components/link-arrow/index.js
  site/components/link-arrow/style.css
  site/pages/what-we-do/cross-functional-slice/index.js
  site/pages/what-we-do/cross-functional-slice/jpg/cross-functional-badgers.jpg
  site/pages/what-we-do/cross-functional-slice/png/big-party.png
  site/pages/what-we-do/cross-functional-slice/png/big-party@2x.png
  site/pages/what-we-do/cross-functional-slice/png/big-party@3x.png
  site/pages/what-we-do/cross-functional-slice/styles.css
  site/pages/what-we-do/index.js
Labels: In Test

#708 Add hubspot buttons
  site/pages/technology/hubspot-btns-images/meetup.png
  site/pages/technology/hubspot-btns-images/read-pdf.png
  site/pages/technology/hubspot-btns-images/slack.png
  site/pages/technology/hubspot-btns-images/webinar.png
  site/pages/technology/hubspot-buttons.js
  site/pages/technology/images/react-meetup.svg
  site/pages/technology/images/slack.svg
  site/pages/technology/index.js
  site/pages/technology/style.css
  site/pages/technology/webinar-signup-slice/index.js
Labels: Tested

#715 What we do style
  site/pages/what-we-do/header-slice/index.js
  site/pages/what-we-do/header-slice/style.css
Labels: Needs testing

#707 Add best company logo
  package.json
  site/pages/join-us/2018-best-small-companies-logo.jpg
  site/pages/join-us/header-container/index.js
  site/pages/join-us/header-container/style.css
  site/pages/join-us/index.js
  site/pages/join-us/style.css
  yarn.lock
Labels: In Test

#712 Redesign MailTo Link
  site/slices/checklist-contact-us-slice/index.js
  site/slices/checklist-contact-us-slice/style.css
Labels: Needs testing

#719 Design tweaks for cross functional slice and what we do
  site/components/colour-box/style.css
  site/pages/what-we-do/cross-functional-slice/index.js
  site/pages/what-we-do/cross-functional-slice/styles.css
  site/pages/what-we-do/header-slice/style.css
Labels: Needs review

#720 Remove unused contact-us code
  .env.example
  README.md
  docs/environment-variables.md
  services/README.md
  services/contact_us.js
  services/index.js
  services/serverless.yaml
  services/ses/index.js
  services/ses/test.js
  site/slices/contact-us-slice/form/index.js
  site/slices/contact-us-slice/form/style.css
  site/slices/contact-us-slice/form/test.js
  site/slices/contact-us-slice/index.js
  site/slices/contact-us-slice/success/index.js
  site/slices/contact-us-slice/success/style.css
  site/slices/contact-us-slice/test.js
Labels: Needs review
