Repository redbadger/website-honestly, pull requests merged in 2018-05, with the labels that each got.

#751 Tech roundtable - April 2018
  site/components/buttons/hubspot-btns-images/meetup.png
  site/components/buttons/hubspot-btns-images/read-pdf.png
  site/components/buttons/hubspot-btns-images/slack.png
  site/components/buttons/hubspot-btns-images/webinar.png
  site/components/buttons/hubspot-buttons.js
  site/components/buttons/index.js
  site/components/buttons/style.css
  site/components/slice/index.js
  site/components/slice/style.css
  site/components/text/index.js
  site/components/text/style.css
  site/pages/technology/hubspot-btns-images/read-pdf.png
  site/pages/technology/images/2018-april-roundtable.png
  site/pages/technology/images/2018-april-roundtable@2x.png
  site/pages/technology/images/2018-april-roundtable@3x.png
  site/pages/technology/index.js
  site/pages/technology/style.css
Labels: Needs testing

#752 Fix case study typography
  site/pages/our-work/case-study-cell/style.css
  site/pages/our-work/case-study/bank/index.js
  site/pages/our-work/case-study/bank/style.css
  site/pages/our-work/case-study/camden-market/index.js
  site/pages/our-work/case-study/camden-market/style.css
  site/pages/our-work/case-study/fortnum-and-mason-digital-transformation/index.js
  site/pages/our-work/case-study/fortnum-and-mason-digital-transformation/style.css
  site/pages/our-work/case-study/fortnum-and-mason/index.js
  site/pages/our-work/case-study/fortnum-and-mason/style.css
  site/pages/our-work/case-study/ft/index.js
  site/pages/our-work/case-study/ft/style.css
  site/pages/our-work/case-study/retailer/index.js
  site/pages/our-work/case-study/retailer/style.css
  site/pages/our-work/case-study/sky-cms/index.js
  site/pages/our-work/case-study/sky-cms/style.css
Labels: In Test

#756 Update open graph tags
  site/components/social/index.js
  site/pages/about-us/index.js
  site/pages/about-us/meta-image.jpg
  site/pages/badger-profile/index.js
  site/pages/event/index.js
  site/pages/event/meta-image.jpg
  site/pages/events/index.js
  site/pages/events/meta-image.jpg
  site/pages/home/index.js
  site/pages/home/meta-image.jpg
  site/pages/home/meta-image.png
  site/pages/job/index.js
  site/pages/job/meta-image.jpg
  site/pages/join-us/index.js
  site/pages/join-us/meta-image.jpg
  site/pages/meet-our-team/index.js
  site/pages/meet-our-team/meta-image.jpg
  site/pages/meet-our-team/meta-image.png
  site/pages/our-work/case-study/bank/index.js
  site/pages/our-work/case-study/bank/meta-image.jpg
  site/pages/our-work/case-study/fortnum-and-mason/index.js
  site/pages/our-work/case-study/fortnum-and-mason/meta-image.jpg
  site/pages/our-work/case-study/ft/index.js
  site/pages/our-work/case-study/ft/meta-image.jpg
  site/pages/our-work/case-study/retailer/images/meta-image.jpg
  site/pages/our-work/case-study/retailer/index.js
  site/pages/our-work/case-study/retailer/meta-image.jpg
  site/pages/our-work/index.js
  site/pages/our-work/meta-image.jpg
  site/pages/our-work/meta-image.png
  site/pages/technology/index.js
  site/pages/technology/meta-image.jpg
  site/pages/what-we-do/index.js
  site/pages/what-we-do/meta-image.jpg
  site/pages/what-we-do/meta-image.png
Labels: WIP

#765 Policies fixes
  package.json
  site/client/index.js
  site/pages/cookie-policy/index.js
  site/pages/privacy-policy/policy.js
  site/pages/privacy-policy/style.css
  yarn.lock
Labels: Needs review

#761 Add client testimonials to the home page
  site/components/cookie-banner/index.js
  site/components/navigator/arrow/index.js
  site/components/navigator/arrow/style.css
  site/components/navigator/item/index.js
  site/components/navigator/item/style.css
  site/pages/about-us/timeline-slice/navigator/index.js
  site/pages/about-us/timeline-slice/navigator/style.css
  site/pages/events/events-list-entry/index.js
  site/pages/home/client-testimonials-slice/index.js
  site/pages/home/client-testimonials-slice/navigator/index.js
  site/pages/home/client-testimonials-slice/navigator/style.css
  site/pages/home/client-testimonials-slice/style.css
  site/pages/home/client-testimonials-slice/testimonial/index.js
  site/pages/home/client-testimonials-slice/testimonial/short-styles.css
  site/pages/home/client-testimonials-slice/testimonial/styles.css
  site/pages/home/client-testimonials-slice/testimonials.js
  site/pages/home/index.js
  site/pages/privacy-policy/policy.js
Labels: Needs review
